# Generated by CMake 2.8.7

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target opencv_core
ADD_LIBRARY(opencv_core SHARED IMPORTED)

# Create imported target opencv_flann
ADD_LIBRARY(opencv_flann SHARED IMPORTED)

# Create imported target opencv_imgproc
ADD_LIBRARY(opencv_imgproc SHARED IMPORTED)

# Create imported target opencv_ml
ADD_LIBRARY(opencv_ml SHARED IMPORTED)

# Create imported target opencv_photo
ADD_LIBRARY(opencv_photo SHARED IMPORTED)

# Create imported target opencv_video
ADD_LIBRARY(opencv_video SHARED IMPORTED)

# Create imported target opencv_imgcodecs
ADD_LIBRARY(opencv_imgcodecs SHARED IMPORTED)

# Create imported target opencv_shape
ADD_LIBRARY(opencv_shape SHARED IMPORTED)

# Create imported target opencv_videoio
ADD_LIBRARY(opencv_videoio SHARED IMPORTED)

# Create imported target opencv_highgui
ADD_LIBRARY(opencv_highgui SHARED IMPORTED)

# Create imported target opencv_objdetect
ADD_LIBRARY(opencv_objdetect SHARED IMPORTED)

# Create imported target opencv_superres
ADD_LIBRARY(opencv_superres SHARED IMPORTED)

# Create imported target opencv_features2d
ADD_LIBRARY(opencv_features2d SHARED IMPORTED)

# Create imported target opencv_calib3d
ADD_LIBRARY(opencv_calib3d SHARED IMPORTED)

# Create imported target opencv_stitching
ADD_LIBRARY(opencv_stitching SHARED IMPORTED)

# Create imported target opencv_videostab
ADD_LIBRARY(opencv_videostab SHARED IMPORTED)

# Import target "opencv_core" for configuration "RELEASE"
SET_PROPERTY(TARGET opencv_core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_core PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sarjak/sarjak_opencv/opencv/release/lib/libopencv_core.so.3.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_core.so.3.1"
  )

# Import target "opencv_flann" for configuration "RELEASE"
SET_PROPERTY(TARGET opencv_flann APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_flann PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core"
  IMPORTED_LOCATION_RELEASE "/home/sarjak/sarjak_opencv/opencv/release/lib/libopencv_flann.so.3.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_flann.so.3.1"
  )

# Import target "opencv_imgproc" for configuration "RELEASE"
SET_PROPERTY(TARGET opencv_imgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_imgproc PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core"
  IMPORTED_LOCATION_RELEASE "/home/sarjak/sarjak_opencv/opencv/release/lib/libopencv_imgproc.so.3.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_imgproc.so.3.1"
  )

# Import target "opencv_ml" for configuration "RELEASE"
SET_PROPERTY(TARGET opencv_ml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_ml PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core"
  IMPORTED_LOCATION_RELEASE "/home/sarjak/sarjak_opencv/opencv/release/lib/libopencv_ml.so.3.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_ml.so.3.1"
  )

# Import target "opencv_photo" for configuration "RELEASE"
SET_PROPERTY(TARGET opencv_photo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_photo PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_imgproc"
  IMPORTED_LOCATION_RELEASE "/home/sarjak/sarjak_opencv/opencv/release/lib/libopencv_photo.so.3.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_photo.so.3.1"
  )

# Import target "opencv_video" for configuration "RELEASE"
SET_PROPERTY(TARGET opencv_video APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_video PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_imgproc"
  IMPORTED_LOCATION_RELEASE "/home/sarjak/sarjak_opencv/opencv/release/lib/libopencv_video.so.3.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_video.so.3.1"
  )

# Import target "opencv_imgcodecs" for configuration "RELEASE"
SET_PROPERTY(TARGET opencv_imgcodecs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_imgcodecs PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "opencv_core;opencv_imgproc"
  IMPORTED_LOCATION_RELEASE "/home/sarjak/sarjak_opencv/opencv/release/lib/libopencv_imgcodecs.so.3.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_imgcodecs.so.3.1"
  )

# Import target "opencv_shape" for configuration "RELEASE"
SET_PROPERTY(TARGET opencv_shape APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_shape PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_imgproc;opencv_video"
  IMPORTED_LOCATION_RELEASE "/home/sarjak/sarjak_opencv/opencv/release/lib/libopencv_shape.so.3.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_shape.so.3.1"
  )

# Import target "opencv_videoio" for configuration "RELEASE"
SET_PROPERTY(TARGET opencv_videoio APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_videoio PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "opencv_core;opencv_imgproc;opencv_imgcodecs"
  IMPORTED_LOCATION_RELEASE "/home/sarjak/sarjak_opencv/opencv/release/lib/libopencv_videoio.so.3.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_videoio.so.3.1"
  )

# Import target "opencv_highgui" for configuration "RELEASE"
SET_PROPERTY(TARGET opencv_highgui APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_highgui PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_videoio"
  IMPORTED_LOCATION_RELEASE "/home/sarjak/sarjak_opencv/opencv/release/lib/libopencv_highgui.so.3.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_highgui.so.3.1"
  )

# Import target "opencv_objdetect" for configuration "RELEASE"
SET_PROPERTY(TARGET opencv_objdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_objdetect PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui"
  IMPORTED_LOCATION_RELEASE "/home/sarjak/sarjak_opencv/opencv/release/lib/libopencv_objdetect.so.3.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_objdetect.so.3.1"
  )

# Import target "opencv_superres" for configuration "RELEASE"
SET_PROPERTY(TARGET opencv_superres APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_superres PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_imgproc;opencv_video;opencv_imgcodecs;opencv_videoio"
  IMPORTED_LOCATION_RELEASE "/home/sarjak/sarjak_opencv/opencv/release/lib/libopencv_superres.so.3.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_superres.so.3.1"
  )

# Import target "opencv_features2d" for configuration "RELEASE"
SET_PROPERTY(TARGET opencv_features2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_features2d PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui"
  IMPORTED_LOCATION_RELEASE "/home/sarjak/sarjak_opencv/opencv/release/lib/libopencv_features2d.so.3.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_features2d.so.3.1"
  )

# Import target "opencv_calib3d" for configuration "RELEASE"
SET_PROPERTY(TARGET opencv_calib3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_calib3d PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d"
  IMPORTED_LOCATION_RELEASE "/home/sarjak/sarjak_opencv/opencv/release/lib/libopencv_calib3d.so.3.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_calib3d.so.3.1"
  )

# Import target "opencv_stitching" for configuration "RELEASE"
SET_PROPERTY(TARGET opencv_stitching APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_stitching PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_objdetect;opencv_features2d;opencv_calib3d"
  IMPORTED_LOCATION_RELEASE "/home/sarjak/sarjak_opencv/opencv/release/lib/libopencv_stitching.so.3.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_stitching.so.3.1"
  )

# Import target "opencv_videostab" for configuration "RELEASE"
SET_PROPERTY(TARGET opencv_videostab APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_videostab PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_photo;opencv_video;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d"
  IMPORTED_LOCATION_RELEASE "/home/sarjak/sarjak_opencv/opencv/release/lib/libopencv_videostab.so.3.1.0"
  IMPORTED_SONAME_RELEASE "libopencv_videostab.so.3.1"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
